"""empty message

Revision ID: 70f1dde9f570
Revises: 8d401039e50e
Create Date: 2022-06-12 20:29:12.536239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f1dde9f570'
down_revision = '8d401039e50e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('past_shows', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('upcoming_shows', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'upcoming_shows')
    op.drop_column('artist', 'past_shows')
    # ### end Alembic commands ###
