"""empty message

Revision ID: a34bc0c69414
Revises: 70f1dde9f570
Create Date: 2022-06-13 00:14:23.902302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34bc0c69414'
down_revision = '70f1dde9f570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'past_shows')
    op.drop_column('artist', 'upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('upcoming_shows', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('past_shows', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
