"""empty message

Revision ID: e54b782f83f6
Revises: 812130d72fb0
Create Date: 2022-06-11 18:18:11.258486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54b782f83f6'
down_revision = '812130d72fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'artist', ['id'])
    op.drop_column('venue', 'upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('upcoming_shows', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'artist', type_='unique')
    # ### end Alembic commands ###
